from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def generate_phase1_report(
    report_path: str | Path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Tạo báo cáo markdown cho baseline phase 1."""
    report_path = Path(report_path)

    q_status = "PASSED" if quality.get("success") else "FAILED"
    sla_status = freshness.get("sla_status", "UNKNOWN")
    retrieval_hit = metrics.get("retrieval_hit_rate", 0.0)
    token_f1 = metrics.get("mean_token_f1", 0.0)
    judge_acc = metrics.get("judge_accuracy", 0.0)
    judge_score = metrics.get("mean_judge_score", 0.0)

    exp_list = quality.get("expectations") or quality.get("results") or []
    eval_count = quality.get("evaluated_expectations", len(exp_list))
    unsuccessful = quality.get("unsuccessful_expectations", sum(1 for e in exp_list if not e.get("success")))

    lines = [
        "# Phase 1 Baseline Pipeline Report",
        "",
        "## 1. Pipeline Overview & Source Summary",
        f"- **Raw records ingested:** {source_summary.get('raw_records', 'N/A')}",
        f"- **Clean records processed:** {source_summary.get('clean_records', 'N/A')}",
        f"- **Embedding model:** `{source_summary.get('embedding_model', 'all-MiniLM-L6-v2')}`",
        f"- **Chroma collection:** `{source_summary.get('collection_name', 'papers-baseline')}`",
        "",
        "## 2. Baseline Benchmark Metrics",
        "| Metric | Value | Target | Status |",
        "| :--- | :--- | :--- | :--- |",
        f"| Test Samples | {metrics.get('samples', 0)} | 10 | Complete |",
        f"| Retrieval Hit Rate | {retrieval_hit:.2%} | >= 80% | {'PASS' if retrieval_hit >= 0.8 else 'WARN'} |",
        f"| Mean Token F1 | {token_f1:.4f} | >= 0.50 | {'PASS' if token_f1 >= 0.5 else 'WARN'} |",
        f"| Judge Accuracy | {judge_acc:.2%} | >= 70% | {'PASS' if judge_acc >= 0.7 else 'WARN'} |",
        f"| Mean Judge Score | {judge_score:.2f} / 5.0 | >= 3.0 | {'PASS' if judge_score >= 3.0 else 'WARN'} |",
        "",
        "## 3. Data Quality Gate (Great Expectations 1.x)",
        f"- **Overall Quality Status:** `{q_status}`",
        f"- **Expectations Evaluated:** {eval_count}",
        f"- **Failed Expectations:** {unsuccessful}",
        "",
        "### Quality Checks Detail",
    ]

    for item in exp_list:
        exp_name = item.get("expectation", "check")
        status_icon = "PASS" if item.get("success") else "FAIL"
        col = item.get("column") or item.get("kwargs", {}).get("column")
        col_str = f" (`{col}`)" if col else ""
        lines.append(f"- [{status_icon}] **{exp_name}**{col_str}")

    lines.extend([
        "",
        "## 4. Freshness SLA Monitoring",
        f"- **SLA Health:** `{sla_status}`",
        f"- **Total Documents:** {freshness.get('total_documents', 'N/A')}",
        f"- **Fresh Documents:** {freshness.get('fresh_documents', 'N/A')}",
        f"- **Stale Documents:** {freshness.get('stale_documents', 'N/A')} ({freshness.get('stale_ratio', 0.0):.1%})",
        f"- **Stale Threshold:** {freshness.get('stale_threshold_days', 180)} days",
        "",
        "---",
        "*Report auto-generated by Baseline Phase 1 Pipeline.*",
    ])

    write_text(report_path, "\n".join(lines) + "\n")


def generate_corruption_report(
    report_path: str | Path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Tạo báo cáo markdown so sánh 3 trạng thái: Baseline, Corrupted, và Repaired."""
    report_path = Path(report_path)

    b_hit = baseline_metrics.get("retrieval_hit_rate", 0.0)
    c_hit = corrupted_metrics.get("retrieval_hit_rate", 0.0)
    r_hit = repaired_metrics.get("retrieval_hit_rate", 0.0)

    b_f1 = baseline_metrics.get("mean_token_f1", 0.0)
    c_f1 = corrupted_metrics.get("mean_token_f1", 0.0)
    r_f1 = repaired_metrics.get("mean_token_f1", 0.0)

    lines = [
        "# Data Corruption & Repair Comparison Report",
        "",
        "## 1. Metric Comparison Across Pipeline Stages",
        "| Metric | Baseline | Corrupted | Repaired | Impact / Delta |",
        "| :--- | :--- | :--- | :--- | :--- |",
        f"| Retrieval Hit Rate | {b_hit:.2%} | {c_hit:.2%} | {r_hit:.2%} | {c_hit - b_hit:+.2%} -> {r_hit - c_hit:+.2%} |",
        f"| Mean Token F1 | {b_f1:.4f} | {c_f1:.4f} | {r_f1:.4f} | {c_f1 - b_f1:+.4f} -> {r_f1 - c_f1:+.4f} |",
        "",
        "## 2. Quality Gate Status",
        f"- **Corrupted Quality Status:** `{'PASSED' if corrupted_quality.get('success') else 'FAILED'}`",
        f"- **Repaired Quality Status:** `{'PASSED' if repaired_quality.get('success') else 'FAILED'}`",
        "",
        "## 3. Freshness SLA Comparison",
        f"- **Corrupted SLA Status:** `{corrupted_freshness.get('sla_status', 'N/A')}` (Stale ratio: {corrupted_freshness.get('stale_ratio', 0.0):.1%})",
        f"- **Repaired SLA Status:** `{repaired_freshness.get('sla_status', 'N/A')}` (Stale ratio: {repaired_freshness.get('stale_ratio', 0.0):.1%})",
        "",
        "---",
        "*Report auto-generated by Corruption Flow Pipeline.*",
    ]

    write_text(report_path, "\n".join(lines) + "\n")
